version: '3.8'
services:
  db:
    container_name: tetrigo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: tetrigo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - tetrigo
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - tetrigo
    depends_on:
      - db

networks:
  tetrigo: