name: cicd
on:
  push:
    branches:
      - gcp-deployment

concurrency:
  group: ${{ github.ref }}

jobs:
  build_deploy:
    uses: ./.github/workflows/build.yml
    with:
      app: tetrigo-web
    secrets: inherit