name: cicd
on:
  push:
    branches:
      - main

jobs:
  web-build-upload:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: gcp login
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}

      - name: docker build & upload
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
