name: deploy

on:
  workflow_call:
    inputs:
      app:
        description: 'Application name'
        type: string
        required: true

env:
  GCP_REPOSITORY: us-west1-docker.pkg.dev

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: prepare version
        run: |
          VERSION=${GITHUB_SHA::7}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_VERSION=${GITHUB_REF/refs\/tags\//}
            echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          fi
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: gcp login
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CRED_JSON }}

      - name: deploy to cloudrun
        uses: google-github-actions/deploy-cloudrun@v2
        env:
          REGISTRY: ${{ env.GCP_REPOSITORY }}/${{ secrets.GCP_PROJECT }}/tetrigo
        with:
          service: tetrigo-web
          image: ${{ env.REGISTRY }}/${{ inputs.app }}:${{ env.VERSION }}
