on:
  pull_request:

name: tests
jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: app tests
        run: go test -v ./...

      - name: build
        run: go build -v ./...

  web-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'

      - name: install dependencies
        run: |
          pushd web/
          npm ci
          npm run build
          popd

#      - name: app tests
#        run: npm test
#
#      - name: build
#        run: npm run build